// <auto-generated />
using System;
using System.Collections.Generic;
using Lidemia.DataAccess.Context;
using Lidemia.DataAccess.Entities.Meta;
using Lidemia.DataAccess.Entities.Misc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lidemia.DataAccess.Migrations
{
    [DbContext(typeof(LidemiaDbContext))]
    partial class LidemiaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lidemia.DataAccess.Entities.AddressEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("address_line1");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("address_line2");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("city");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("PostalIndex")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("postal_index");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("region");

                    b.Property<int>("RowVersion")
                        .HasColumnType("integer")
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.HasKey("Id")
                        .HasName("pk_addresses");

                    b.HasIndex("CustomerId", "IsActive")
                        .HasDatabaseName("ix_addresses_customer_id_is_active");

                    b.HasIndex("CustomerId", "IsDefault", "IsActive")
                        .HasDatabaseName("ix_addresses_customer_id_is_default_is_active");

                    b.ToTable("addresses", (string)null);
                });

            modelBuilder.Entity("Lidemia.DataAccess.Entities.AuthTokenEntity", b =>
                {
                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("access_token");

                    b.Property<DateTimeOffset>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<int>("EntityType")
                        .HasColumnType("integer")
                        .HasColumnName("entity_type");

                    b.Property<DateTimeOffset?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("refresh_token");

                    b.Property<int>("RowVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_auth_tokens_is_active");

                    b.HasIndex("AccessToken", "IsActive")
                        .HasDatabaseName("ix_auth_tokens_access_token_is_active");

                    b.HasIndex("EntityId", "IsActive")
                        .HasDatabaseName("ix_auth_tokens_entity_id_is_active");

                    b.ToTable("auth_tokens", (string)null);
                });

            modelBuilder.Entity("Lidemia.DataAccess.Entities.CustomerAddressEntity", b =>
                {
                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<long>("AddressId")
                        .HasColumnType("bigint")
                        .HasColumnName("address_id");

                    b.Property<Guid>("AddressId1")
                        .HasColumnType("uuid")
                        .HasColumnName("address_id1");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("RowVersion")
                        .HasColumnType("integer")
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.HasKey("CustomerId", "AddressId")
                        .HasName("pk_customer_addresses");

                    b.HasIndex("AddressId1")
                        .HasDatabaseName("ix_customer_addresses_address_id1");

                    b.HasIndex("CustomerId", "IsActive")
                        .HasDatabaseName("ix_customer_addresses_customer_id_is_active");

                    b.ToTable("customer_addresses", (string)null);
                });

            modelBuilder.Entity("Lidemia.DataAccess.Entities.CustomerEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasDefaultValueSql("service.next_id()");

                    b.Property<DateTimeOffset>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text")
                        .HasColumnName("logo_url");

                    b.Property<CustomerMetadata>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("RowVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("row_version");

                    b.Property<string>("Tin")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tin");

                    b.Property<DateTimeOffset?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_customers_is_active");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_customers_user_id");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("Lidemia.DataAccess.Entities.OrderEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasDefaultValueSql("service.next_id()");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTimeOffset>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsFinishConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_finish_confirmed");

                    b.Property<DateTime?>("LastStatusUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_status_update");

                    b.Property<OrderMetadata>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("number");

                    b.Property<long?>("PromoCodeId")
                        .HasColumnType("bigint")
                        .HasColumnName("promo_code_id");

                    b.Property<int>("RowVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("row_version");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_orders_is_active");

                    b.HasIndex("PromoCodeId")
                        .HasDatabaseName("ix_orders_promo_code_id");

                    b.HasIndex("CustomerId", "IsActive")
                        .HasDatabaseName("ix_orders_customer_id_is_active");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("Lidemia.DataAccess.Entities.OrderItemEntity", b =>
                {
                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision")
                        .HasColumnName("quantity");

                    b.Property<int>("RowVersion")
                        .HasColumnType("integer")
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.HasKey("OrderId", "ProductId")
                        .HasName("pk_order_items");

                    b.HasIndex("OrderId", "IsActive")
                        .HasDatabaseName("ix_order_items_order_id_is_active");

                    b.HasIndex("ProductId", "IsActive")
                        .HasDatabaseName("ix_order_items_product_id_is_active");

                    b.ToTable("order_items", (string)null);
                });

            modelBuilder.Entity("Lidemia.DataAccess.Entities.PasswordResetEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<int>("EntityType")
                        .HasColumnType("integer")
                        .HasColumnName("entity_type");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("RowVersion")
                        .HasColumnType("integer")
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_password_resets");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_password_resets_code");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_password_resets_user_id");

                    b.ToTable("password_resets", (string)null);
                });

            modelBuilder.Entity("Lidemia.DataAccess.Entities.PhotoEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasDefaultValueSql("service.next_id()");

                    b.Property<DateTimeOffset>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ExtraPath")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("extra_path");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_processed");

                    b.Property<string>("LargeThumbUrl")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("large_thumb_url");

                    b.Property<string>("MediumThumbUrl")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("medium_thumb_url");

                    b.Property<int>("RowVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("row_version");

                    b.Property<string>("SmallThumbUrl")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("small_thumb_url");

                    b.Property<DateTimeOffset?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_photos");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_photos_is_active");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_photos_user_id");

                    b.ToTable("photos", (string)null);
                });

            modelBuilder.Entity("Lidemia.DataAccess.Entities.ProductCategoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasDefaultValueSql("service.next_id()");

                    b.Property<DateTimeOffset>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DescriptionKey")
                        .HasColumnType("text")
                        .HasColumnName("description_key");

                    b.Property<string>("ImageClass")
                        .HasColumnType("text")
                        .HasColumnName("image_class");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_key");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_id");

                    b.Property<int>("RowVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.HasKey("Id")
                        .HasName("pk_product_categories");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_product_categories_is_active");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_product_categories_parent_id");

                    b.ToTable("product_categories", (string)null);
                });

            modelBuilder.Entity("Lidemia.DataAccess.Entities.ProductEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasDefaultValueSql("service.next_id()");

                    b.Property<int?>("AvailabilityType")
                        .HasColumnType("integer")
                        .HasColumnName("availability_type");

                    b.Property<double?>("AverageRatingOverall")
                        .HasColumnType("double precision")
                        .HasColumnName("average_rating_overall");

                    b.Property<double?>("AverageRatingRecent")
                        .HasColumnType("double precision")
                        .HasColumnName("average_rating_recent");

                    b.Property<long?>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("DiscountEndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("discount_end_date");

                    b.Property<decimal?>("DiscountPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("discount_price");

                    b.Property<DateTime?>("DiscountStartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("discount_start_date");

                    b.Property<DateTime?>("FirstSeenDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_date");

                    b.Property<bool>("HasCurrentDiscount")
                        .HasColumnType("boolean")
                        .HasColumnName("has_current_discount");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDiscount")
                        .HasColumnType("boolean")
                        .HasColumnName("is_discount");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_visible");

                    b.Property<double?>("MaxQuantity")
                        .HasColumnType("double precision")
                        .HasColumnName("max_quantity");

                    b.Property<double?>("MinQuantity")
                        .HasColumnType("double precision")
                        .HasColumnName("min_quantity");

                    b.Property<int?>("OrderRank")
                        .HasColumnType("integer")
                        .HasColumnName("order_rank");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_id");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<int?>("PriceUnit")
                        .HasColumnType("integer")
                        .HasColumnName("price_unit");

                    b.Property<long?>("PrimaryPhotoId")
                        .HasColumnType("bigint")
                        .HasColumnName("primary_photo_id");

                    b.Property<int>("RowVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("row_version");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("text")
                        .HasColumnName("short_description");

                    b.Property<string>("Sku")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sku");

                    b.Property<string>("Slug")
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<long>("SupplierId")
                        .HasColumnType("bigint")
                        .HasColumnName("supplier_id");

                    b.Property<string>("Title")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("title");

                    b.Property<int>("TotalRates")
                        .HasColumnType("integer")
                        .HasColumnName("total_rates");

                    b.Property<DateTimeOffset?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_products_category_id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_products_is_active");

                    b.HasIndex("IsVisible")
                        .HasDatabaseName("ix_products_is_visible");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_products_parent_id");

                    b.HasIndex("PrimaryPhotoId")
                        .HasDatabaseName("ix_products_primary_photo_id");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_products_supplier_id");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("Lidemia.DataAccess.Entities.ProductFeedbackEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<string>("Comment")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("comment");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<byte>("Rate")
                        .HasColumnType("smallint")
                        .HasColumnName("rate");

                    b.Property<int>("RowVersion")
                        .HasColumnType("integer")
                        .HasColumnName("row_version");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.HasKey("Id")
                        .HasName("pk_product_feedbacks");

                    b.HasIndex("CustomerId", "IsActive")
                        .HasDatabaseName("ix_product_feedbacks_customer_id_is_active");

                    b.HasIndex("ProductId", "IsActive")
                        .HasDatabaseName("ix_product_feedbacks_product_id_is_active");

                    b.HasIndex("ProductId", "State", "IsActive")
                        .HasDatabaseName("ix_product_feedbacks_product_id_state_is_active");

                    b.ToTable("product_feedbacks", (string)null);
                });

            modelBuilder.Entity("Lidemia.DataAccess.Entities.ProductPhotoEntity", b =>
                {
                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<long>("PhotoId")
                        .HasColumnType("bigint")
                        .HasColumnName("photo_id");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<int>("RowVersion")
                        .HasColumnType("integer")
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.HasIndex("PhotoId")
                        .HasDatabaseName("ix_products_photos_photo_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_products_photos_product_id");

                    b.ToTable("products_photos", (string)null);
                });

            modelBuilder.Entity("Lidemia.DataAccess.Entities.PromoCodeEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasDefaultValueSql("service.next_id()");

                    b.PrimitiveCollection<long[]>("AllowedCategories")
                        .IsRequired()
                        .HasColumnType("bigint[]")
                        .HasColumnName("allowed_categories");

                    b.PrimitiveCollection<long[]>("AllowedCustomers")
                        .IsRequired()
                        .HasColumnType("bigint[]")
                        .HasColumnName("allowed_customers");

                    b.PrimitiveCollection<long[]>("AllowedProducts")
                        .IsRequired()
                        .HasColumnType("bigint[]")
                        .HasColumnName("allowed_products");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DiscountType")
                        .HasColumnType("integer")
                        .HasColumnName("discount_type");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsOneTime")
                        .HasColumnType("boolean")
                        .HasColumnName("is_one_time");

                    b.Property<decimal?>("MaxAllowedTotalSum")
                        .HasColumnType("numeric")
                        .HasColumnName("max_allowed_total_sum");

                    b.Property<int?>("MaxUsages")
                        .HasColumnType("integer")
                        .HasColumnName("max_usages");

                    b.Property<int>("RowVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("row_version");

                    b.Property<DateTime?>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<long>("SupplierId")
                        .HasColumnType("bigint")
                        .HasColumnName("supplier_id");

                    b.Property<int>("TotalUsages")
                        .HasColumnType("integer")
                        .HasColumnName("total_usages");

                    b.Property<DateTimeOffset?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_promo_codes");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_promo_codes_is_active");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_promo_codes_supplier_id");

                    b.ToTable("promo_codes", (string)null);
                });

            modelBuilder.Entity("Lidemia.DataAccess.Entities.ShoppingCartEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<IEnumerable<ShoppingCartItemDbModel>>("Items")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("items");

                    b.Property<int>("RowVersion")
                        .HasColumnType("integer")
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_shopping_carts");

                    b.HasIndex("UserId", "IsActive")
                        .HasDatabaseName("ix_shopping_carts_user_id_is_active");

                    b.ToTable("shopping_carts", (string)null);
                });

            modelBuilder.Entity("Lidemia.DataAccess.Entities.SupplierAddressEntity", b =>
                {
                    b.Property<long>("SupplierId")
                        .HasColumnType("bigint")
                        .HasColumnName("supplier_id");

                    b.Property<long>("AddressId")
                        .HasColumnType("bigint")
                        .HasColumnName("address_id");

                    b.Property<Guid>("AddressId1")
                        .HasColumnType("uuid")
                        .HasColumnName("address_id1");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("RowVersion")
                        .HasColumnType("integer")
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.HasKey("SupplierId", "AddressId")
                        .HasName("pk_suppliers_addresses");

                    b.HasIndex("AddressId1")
                        .HasDatabaseName("ix_suppliers_addresses_address_id1");

                    b.HasIndex("SupplierId", "IsActive")
                        .HasDatabaseName("ix_suppliers_addresses_supplier_id_is_active");

                    b.ToTable("suppliers_addresses", (string)null);
                });

            modelBuilder.Entity("Lidemia.DataAccess.Entities.SupplierEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasDefaultValueSql("service.next_id()");

                    b.Property<string>("ActualAddress")
                        .HasColumnType("text")
                        .HasColumnName("actual_address");

                    b.Property<string>("ContactPersonName")
                        .HasColumnType("text")
                        .HasColumnName("contact_person_name");

                    b.Property<string>("ContactPersonRole")
                        .HasColumnType("text")
                        .HasColumnName("contact_person_role");

                    b.Property<string>("CoverUrl")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("cover_url");

                    b.Property<DateTimeOffset>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Inn")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("inn");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_email_confirmed");

                    b.Property<string>("LegalAddress")
                        .HasColumnType("text")
                        .HasColumnName("legal_address");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("logo_url");

                    b.Property<SupplierMetadata>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("name");

                    b.Property<string>("Ogrn")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("ogrn");

                    b.Property<int>("OrganizationType")
                        .HasColumnType("integer")
                        .HasColumnName("organization_type");

                    b.Property<int>("RowVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("row_version");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("text")
                        .HasColumnName("short_description");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_suppliers");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_suppliers_is_active");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_suppliers_user_id");

                    b.ToTable("suppliers", (string)null);
                });

            modelBuilder.Entity("Lidemia.DataAccess.Entities.SupplierStatsEntity", b =>
                {
                    b.Property<double>("AverageRating")
                        .HasColumnType("double precision")
                        .HasColumnName("average_rating");

                    b.Property<long>("SupplierId")
                        .HasColumnType("bigint")
                        .HasColumnName("supplier_id");

                    b.Property<int>("TotalOrders")
                        .HasColumnType("integer")
                        .HasColumnName("total_orders");

                    b.Property<int>("TotalProducts")
                        .HasColumnType("integer")
                        .HasColumnName("total_products");

                    b.ToTable("suppliers_stats", (string)null);
                });

            modelBuilder.Entity("Lidemia.DataAccess.Entities.UserEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasDefaultValueSql("service.next_id()");

                    b.Property<DateTimeOffset>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("EmailNormalized")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email_normalized");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_blocked");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_salt");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("phone");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<int>("RowVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("EmailNormalized")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email_normalized");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_users_is_active");

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasDatabaseName("ix_users_phone");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Lidemia.DataAccess.Entities.WishListEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("ItemsCount")
                        .HasColumnType("integer")
                        .HasColumnName("items_count");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<int>("RowVersion")
                        .HasColumnType("integer")
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.HasKey("Id")
                        .HasName("pk_wish_lists");

                    b.HasIndex("CustomerId", "IsActive")
                        .HasDatabaseName("ix_wish_lists_customer_id_is_active");

                    b.ToTable("wish_lists", (string)null);
                });

            modelBuilder.Entity("Lidemia.DataAccess.Entities.WishListItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<int>("RowVersion")
                        .HasColumnType("integer")
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.Property<Guid>("WishListId")
                        .HasColumnType("uuid")
                        .HasColumnName("wish_list_id");

                    b.HasKey("Id")
                        .HasName("pk_wish_list_items");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_wish_list_items_product_id");

                    b.HasIndex("WishListId", "IsActive")
                        .HasDatabaseName("ix_wish_list_items_wish_list_id_is_active");

                    b.HasIndex("WishListId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("ix_wish_list_items_wish_list_id_product_id");

                    b.ToTable("wish_list_items", (string)null);
                });

            modelBuilder.Entity("Lidemia.DataAccess.Entities.AddressEntity", b =>
                {
                    b.HasOne("Lidemia.DataAccess.Entities.CustomerEntity", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_addresses_customers_customer_id");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Lidemia.DataAccess.Entities.CustomerAddressEntity", b =>
                {
                    b.HasOne("Lidemia.DataAccess.Entities.AddressEntity", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_customer_addresses_addresses_address_id1");

                    b.HasOne("Lidemia.DataAccess.Entities.CustomerEntity", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_customer_addresses_customers_customer_id");

                    b.Navigation("Address");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Lidemia.DataAccess.Entities.CustomerEntity", b =>
                {
                    b.HasOne("Lidemia.DataAccess.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_customers_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lidemia.DataAccess.Entities.OrderEntity", b =>
                {
                    b.HasOne("Lidemia.DataAccess.Entities.CustomerEntity", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_orders_customers_customer_id");

                    b.HasOne("Lidemia.DataAccess.Entities.PromoCodeEntity", "PromoCode")
                        .WithMany()
                        .HasForeignKey("PromoCodeId")
                        .HasConstraintName("fk_orders_promo_codes_promo_code_id");

                    b.Navigation("Customer");

                    b.Navigation("PromoCode");
                });

            modelBuilder.Entity("Lidemia.DataAccess.Entities.OrderItemEntity", b =>
                {
                    b.HasOne("Lidemia.DataAccess.Entities.OrderEntity", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_items_orders_order_id");

                    b.HasOne("Lidemia.DataAccess.Entities.ProductEntity", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_items_products_product_id");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Lidemia.DataAccess.Entities.PasswordResetEntity", b =>
                {
                    b.HasOne("Lidemia.DataAccess.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_password_resets_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lidemia.DataAccess.Entities.PhotoEntity", b =>
                {
                    b.HasOne("Lidemia.DataAccess.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_photos_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lidemia.DataAccess.Entities.ProductCategoryEntity", b =>
                {
                    b.HasOne("Lidemia.DataAccess.Entities.ProductCategoryEntity", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .HasConstraintName("fk_product_categories_product_categories_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Lidemia.DataAccess.Entities.ProductEntity", b =>
                {
                    b.HasOne("Lidemia.DataAccess.Entities.ProductCategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("fk_products_product_categories_category_id");

                    b.HasOne("Lidemia.DataAccess.Entities.ProductEntity", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .HasConstraintName("fk_products_products_parent_id");

                    b.HasOne("Lidemia.DataAccess.Entities.PhotoEntity", "PrimaryPhoto")
                        .WithMany()
                        .HasForeignKey("PrimaryPhotoId")
                        .HasConstraintName("fk_products_photos_primary_photo_id");

                    b.HasOne("Lidemia.DataAccess.Entities.SupplierEntity", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_products_suppliers_supplier_id");

                    b.Navigation("Category");

                    b.Navigation("Parent");

                    b.Navigation("PrimaryPhoto");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Lidemia.DataAccess.Entities.ProductFeedbackEntity", b =>
                {
                    b.HasOne("Lidemia.DataAccess.Entities.CustomerEntity", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_feedbacks_customers_customer_id");

                    b.HasOne("Lidemia.DataAccess.Entities.ProductEntity", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_feedbacks_products_product_id");

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Lidemia.DataAccess.Entities.ProductPhotoEntity", b =>
                {
                    b.HasOne("Lidemia.DataAccess.Entities.PhotoEntity", "Photo")
                        .WithMany()
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_products_photos_photos_photo_id");

                    b.HasOne("Lidemia.DataAccess.Entities.ProductEntity", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_products_photos_products_product_id");

                    b.Navigation("Photo");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Lidemia.DataAccess.Entities.PromoCodeEntity", b =>
                {
                    b.HasOne("Lidemia.DataAccess.Entities.SupplierEntity", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_promo_codes_suppliers_supplier_id");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Lidemia.DataAccess.Entities.ShoppingCartEntity", b =>
                {
                    b.HasOne("Lidemia.DataAccess.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shopping_carts_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lidemia.DataAccess.Entities.SupplierAddressEntity", b =>
                {
                    b.HasOne("Lidemia.DataAccess.Entities.AddressEntity", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_suppliers_addresses_addresses_address_id1");

                    b.HasOne("Lidemia.DataAccess.Entities.SupplierEntity", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_suppliers_addresses_suppliers_supplier_id");

                    b.Navigation("Address");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Lidemia.DataAccess.Entities.SupplierEntity", b =>
                {
                    b.HasOne("Lidemia.DataAccess.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_suppliers_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lidemia.DataAccess.Entities.WishListEntity", b =>
                {
                    b.HasOne("Lidemia.DataAccess.Entities.CustomerEntity", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wish_lists_customers_customer_id");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Lidemia.DataAccess.Entities.WishListItemEntity", b =>
                {
                    b.HasOne("Lidemia.DataAccess.Entities.ProductEntity", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wish_list_items_products_product_id");

                    b.HasOne("Lidemia.DataAccess.Entities.WishListEntity", "WishList")
                        .WithMany()
                        .HasForeignKey("WishListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wish_list_items_wish_lists_wish_list_id");

                    b.Navigation("Product");

                    b.Navigation("WishList");
                });

            modelBuilder.Entity("Lidemia.DataAccess.Entities.OrderEntity", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
