<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
		<PackageReference Include="SolrNet" Version="1.2.1" />
		<PackageReference Include="SolrNet.Microsoft.DependencyInjection" Version="1.2.1" />
		<PackageReference Include="Scrutor" Version="7.0.0" />
	</ItemGroup>

</Project>