/* COUNTRIES */

INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('AF','AFGHANISTAN','Afghanistan','AFG','004', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('AL','ALBANIA','Albania','ALB','008', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('DZ','ALGERIA','Algeria','DZA','012', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('AS','AMERICAN SAMOA','American Samoa','ASM','016', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('AD','ANDORRA','Andorra','AND','020', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('AO','ANGOLA','Angola','AGO','024', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('AI','ANGUILLA','Anguilla','AIA','660', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('AQ','ANTARCTICA','Antarctica','ANT','0', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('AG','ANTIGUA AND BARBUDA','Antigua and Barbuda','ATG','028', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('AR','ARGENTINA','Argentina','ARG','032', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('AM','ARMENIA','Armenia','ARM','051', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('AW','ARUBA','Aruba','ABW','533', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('AU','AUSTRALIA','Australia','AUS','036', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('AT','AUSTRIA','Austria','AUT','040', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('AZ','AZERBAIJAN','Azerbaijan','AZE','031', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('BS','BAHAMAS','Bahamas','BHS','044', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('BH','BAHRAIN','Bahrain','BHR','048', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('BD','BANGLADESH','Bangladesh','BGD','050', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('BB','BARBADOS','Barbados','BRB','052', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('BY','BELARUS','Belarus','BLR','112', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('BE','BELGIUM','Belgium','BEL','056', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('BZ','BELIZE','Belize','BLZ','084', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('BJ','BENIN','Benin','BEN','204', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('BM','BERMUDA','Bermuda','BMU','060', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('BT','BHUTAN','Bhutan','BTN','064', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('BO','BOLIVIA','Bolivia','BOL','068', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('BA','BOSNIA AND HERZEGOVINA','Bosnia and Herzegovina','BIH','070', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('BW','BOTSWANA','Botswana','BWA','072', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('BV','BOUVET ISLAND','Bouvet Island','BOI','0', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('BR','BRAZIL','Brazil','BRA','076', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('IO','BRITISH INDIAN OCEAN TERRITORY','British Indian Ocean Territory','BIO','0', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('BN','BRUNEI DARUSSALAM','Brunei Darussalam','BRN','096', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('BG','BULGARIA','Bulgaria','BGR','100', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('BF','BURKINA FASO','Burkina Faso','BFA','854', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('BI','BURUNDI','Burundi','BDI','108', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('KH','CAMBODIA','Cambodia','KHM','116', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('CM','CAMEROON','Cameroon','CMR','120', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('CA','CANADA','Canada','CAN','124', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('CV','CAPE VERDE','Cape Verde','CPV','132', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('KY','CAYMAN ISLANDS','Cayman Islands','CYM','136', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('CF','CENTRAL AFRICAN REPUBLIC','Central African Republic','CAF','140', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('TD','CHAD','Chad','TCD','148', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('CL','CHILE','Chile','CHL','152', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('CN','CHINA','China','CHN','156', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('CX','CHRISTMAS ISLAND','Christmas Island','CHR','0', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('CC','COCOS (KEELING) ISLANDS','Cocos (Keeling) Islands','COC','0', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('CO','COLOMBIA','Colombia','COL','170', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('KM','COMOROS','Comoros','COM','174', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('CG','CONGO','Congo','COG','178', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('CD','CONGO, THE DEMOCRATIC REPUBLIC OF THE','Congo, the Democratic Republic of the','COD','180', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('CK','COOK ISLANDS','Cook Islands','COK','184', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('CR','COSTA RICA','Costa Rica','CRI','188', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('CI','COTE D''IVOIRE','Cote D''Ivoire','CIV','384', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('HR','CROATIA','Croatia','HRV','191', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('CU','CUBA','Cuba','CUB','192', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('CY','CYPRUS','Cyprus','CYP','196', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('CZ','CZECH REPUBLIC','Czech Republic','CZE','203', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('DK','DENMARK','Denmark','DNK','208', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('DJ','DJIBOUTI','Djibouti','DJI','262', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('DM','DOMINICA','Dominica','DMA','212', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('DO','DOMINICAN REPUBLIC','Dominican Republic','DOM','214', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('EC','ECUADOR','Ecuador','ECU','218', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('EG','EGYPT','Egypt','EGY','818', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('SV','EL SALVADOR','El Salvador','SLV','222', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('GQ','EQUATORIAL GUINEA','Equatorial Guinea','GNQ','226', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('ER','ERITREA','Eritrea','ERI','232', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('EE','ESTONIA','Estonia','EST','233', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('ET','ETHIOPIA','Ethiopia','ETH','231', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('FK','FALKLAND ISLANDS (MALVINAS)','Falkland Islands (Malvinas)','FLK','238', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('FO','FAROE ISLANDS','Faroe Islands','FRO','234', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('FJ','FIJI','Fiji','FJI','242', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('FI','FINLAND','Finland','FIN','246', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('FR','FRANCE','France','FRA','250', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('GF','FRENCH GUIANA','French Guiana','GUF','254', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('PF','FRENCH POLYNESIA','French Polynesia','PYF','258', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('TF','FRENCH SOUTHERN TERRITORIES','French Southern Territories','FST', '0', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('GA','GABON','Gabon','GAB','266', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('GM','GAMBIA','Gambia','GMB','270', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('GE','GEORGIA','Georgia','GEO','268', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('DE','GERMANY','Germany','DEU','276', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('GH','GHANA','Ghana','GHA','288', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('GI','GIBRALTAR','Gibraltar','GIB','292', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('GR','GREECE','Greece','GRC','300', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('GL','GREENLAND','Greenland','GRL','304', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('GD','GRENADA','Grenada','GRD','308', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('GP','GUADELOUPE','Guadeloupe','GLP','312', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('GU','GUAM','Guam','GUM','316', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('GT','GUATEMALA','Guatemala','GTM','320', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('GN','GUINEA','Guinea','GIN','324', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('GW','GUINEA-BISSAU','Guinea-Bissau','GNB','624', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('GY','GUYANA','Guyana','GUY','328', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('HT','HAITI','Haiti','HTI','332', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('HM','HEARD ISLAND AND MCDONALD ISLANDS','Heard Island and Mcdonald Islands','HIM','0', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('VA','HOLY SEE (VATICAN CITY STATE)','Holy See (Vatican City State)','VAT','336', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('HN','HONDURAS','Honduras','HND','340', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('HK','HONG KONG','Hong Kong','HKG','344', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('HU','HUNGARY','Hungary','HUN','348', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('IS','ICELAND','Iceland','ISL','352', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('IN','INDIA','India','IND','356', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('ID','INDONESIA','Indonesia','IDN','360', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('IR','IRAN, ISLAMIC REPUBLIC OF','Iran, Islamic Republic of','IRN','364', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('IQ','IRAQ','Iraq','IRQ','368', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('IE','IRELAND','Ireland','IRL','372', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('IL','ISRAEL','Israel','ISR','376', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('IT','ITALY','Italy','ITA','380', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('JM','JAMAICA','Jamaica','JAM','388', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('JP','JAPAN','Japan','JPN','392', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('JO','JORDAN','Jordan','JOR','400', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('KZ','KAZAKHSTAN','Kazakhstan','KAZ','398', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('KE','KENYA','Kenya','KEN','404', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('KI','KIRIBATI','Kiribati','KIR','296', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('KP','KOREA, DEMOCRATIC PEOPLE''S REPUBLIC OF','Korea, Democratic People''s Republic of','PRK','408', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('KR','KOREA, REPUBLIC OF','Korea, Republic of','KOR','410', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('KW','KUWAIT','Kuwait','KWT','414', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('KG','KYRGYZSTAN','Kyrgyzstan','KGZ','417', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('LA','LAO PEOPLE''S DEMOCRATIC REPUBLIC','Lao People''s Democratic Republic','LAO','418', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('LV','LATVIA','Latvia','LVA','428', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('LB','LEBANON','Lebanon','LBN','422', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('LS','LESOTHO','Lesotho','LSO','426', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('LR','LIBERIA','Liberia','LBR','430', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('LY','LIBYAN ARAB JAMAHIRIYA','Libyan Arab Jamahiriya','LBY','434', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('LI','LIECHTENSTEIN','Liechtenstein','LIE','438', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('LT','LITHUANIA','Lithuania','LTU','440', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('LU','LUXEMBOURG','Luxembourg','LUX','442', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('MO','MACAO','Macao','MAC','446', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('MK','MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF','Macedonia, the Former Yugoslav Republic of','MKD','807', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('MG','MADAGASCAR','Madagascar','MDG','450', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('MW','MALAWI','Malawi','MWI','454', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('MY','MALAYSIA','Malaysia','MYS','458', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('MV','MALDIVES','Maldives','MDV','462', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('ML','MALI','Mali','MLI','466', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('MT','MALTA','Malta','MLT','470', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('MH','MARSHALL ISLANDS','Marshall Islands','MHL','584', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('MQ','MARTINIQUE','Martinique','MTQ','474', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('MR','MAURITANIA','Mauritania','MRT','478', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('MU','MAURITIUS','Mauritius','MUS','480', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('YT','MAYOTTE','Mayotte','MAY','0', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('MX','MEXICO','Mexico','MEX','484', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('FM','MICRONESIA, FEDERATED STATES OF','Micronesia, Federated States of','FSM','583', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('MD','MOLDOVA, REPUBLIC OF','Moldova, Republic of','MDA','498', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('MC','MONACO','Monaco','MCO','492', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('MN','MONGOLIA','Mongolia','MNG','496', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('MS','MONTSERRAT','Montserrat','MSR','500', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('MA','MOROCCO','Morocco','MAR','504', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('MZ','MOZAMBIQUE','Mozambique','MOZ','508', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('MM','MYANMAR','Myanmar','MMR','104', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('NA','NAMIBIA','Namibia','NAM','516', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('NR','NAURU','Nauru','NRU','520', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('NP','NEPAL','Nepal','NPL','524', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('NL','NETHERLANDS','Netherlands','NLD','528', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('AN','NETHERLANDS ANTILLES','Netherlands Antilles','ANT','530', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('NC','NEW CALEDONIA','New Caledonia','NCL','540', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('NZ','NEW ZEALAND','New Zealand','NZL','554', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('NI','NICARAGUA','Nicaragua','NIC','558', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('NE','NIGER','Niger','NER','562', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('NG','NIGERIA','Nigeria','NGA','566', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('NU','NIUE','Niue','NIU','570', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('NF','NORFOLK ISLAND','Norfolk Island','NFK','574', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('MP','NORTHERN MARIANA ISLANDS','Northern Mariana Islands','MNP','580', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('NO','NORWAY','Norway','NOR','578', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('OM','OMAN','Oman','OMN','512', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('PK','PAKISTAN','Pakistan','PAK','586', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('PW','PALAU','Palau','PLW','585', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('PS','PALESTINIAN TERRITORY, OCCUPIED','Palestinian Territory, Occupied','PTO','0', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('PA','PANAMA','Panama','PAN','591', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('PG','PAPUA NEW GUINEA','Papua New Guinea','PNG','598', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('PY','PARAGUAY','Paraguay','PRY','600', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('PE','PERU','Peru','PER','604', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('PH','PHILIPPINES','Philippines','PHL','608', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('PN','PITCAIRN','Pitcairn','PCN','612', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('PL','POLAND','Poland','POL','616', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('PT','PORTUGAL','Portugal','PRT','620', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('PR','PUERTO RICO','Puerto Rico','PRI','630', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('QA','QATAR','Qatar','QAT','634', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('RE','REUNION','Reunion','REU','638', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('RO','ROMANIA','Romania','ROM','642', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('RU','RUSSIAN FEDERATION','Russian Federation','RUS','643', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('RW','RWANDA','Rwanda','RWA','646', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('SH','SAINT HELENA','Saint Helena','SHN','654', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('KN','SAINT KITTS AND NEVIS','Saint Kitts and Nevis','KNA','659', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('LC','SAINT LUCIA','Saint Lucia','LCA','662', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('PM','SAINT PIERRE AND MIQUELON','Saint Pierre and Miquelon','SPM','666', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('VC','SAINT VINCENT AND THE GRENADINES','Saint Vincent and the Grenadines','VCT','670', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('WS','SAMOA','Samoa','WSM','882', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('SM','SAN MARINO','San Marino','SMR','674', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('ST','SAO TOME AND PRINCIPE','Sao Tome and Principe','STP','678', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('SA','SAUDI ARABIA','Saudi Arabia','SAU','682', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('SN','SENEGAL','Senegal','SEN','686', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('CS','SERBIA AND MONTENEGRO','Serbia and Montenegro','SAM','0', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('SC','SEYCHELLES','Seychelles','SYC','690', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('SL','SIERRA LEONE','Sierra Leone','SLE','694', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('SG','SINGAPORE','Singapore','SGP','702', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('SK','SLOVAKIA','Slovakia','SVK','703', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('SI','SLOVENIA','Slovenia','SVN','705', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('SB','SOLOMON ISLANDS','Solomon Islands','SLB','090', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('SO','SOMALIA','Somalia','SOM','706', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('ZA','SOUTH AFRICA','South Africa','ZAF','710', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('GS','SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS','South Georgia and the South Sandwich Islands','SEG','0', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('ES','SPAIN','Spain','ESP','724', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('LK','SRI LANKA','Sri Lanka','LKA','144', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('SD','SUDAN','Sudan','SDN','736', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('SR','SURINAME','Suriname','SUR','740', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('SJ','SVALBARD AND JAN MAYEN','Svalbard and Jan Mayen','SJM','744', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('SZ','SWAZILAND','Swaziland','SWZ','748', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('SE','SWEDEN','Sweden','SWE','752', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('CH','SWITZERLAND','Switzerland','CHE','756', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('SY','SYRIAN ARAB REPUBLIC','Syrian Arab Republic','SYR','760', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('TW','TAIWAN, PROVINCE OF CHINA','Taiwan, Province of China','TWN','158', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('TJ','TAJIKISTAN','Tajikistan','TJK','762', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('TZ','TANZANIA, UNITED REPUBLIC OF','Tanzania, United Republic of','TZA','834', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('TH','THAILAND','Thailand','THA','764', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('TL','TIMOR-LESTE','Timor-Leste','TLE','0', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('TG','TOGO','Togo','TGO','768', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('TK','TOKELAU','Tokelau','TKL','772', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('TO','TONGA','Tonga','TON','776', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('TT','TRINIDAD AND TOBAGO','Trinidad and Tobago','TTO','780', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('TN','TUNISIA','Tunisia','TUN','788', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('TR','TURKEY','Turkey','TUR','792', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('TM','TURKMENISTAN','Turkmenistan','TKM','795', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('TC','TURKS AND CAICOS ISLANDS','Turks and Caicos Islands','TCA','796', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('TV','TUVALU','Tuvalu','TUV','798', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('UG','UGANDA','Uganda','UGA','800', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('UA','UKRAINE','Ukraine','UKR','804', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('AE','UNITED ARAB EMIRATES','United Arab Emirates','ARE','784', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('GB','UNITED KINGDOM','United Kingdom','GBR','826', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('US','UNITED STATES','United States','USA','840', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('UM','UNITED STATES MINOR OUTLYING ISLANDS','United States Minor Outlying Islands','USM','0', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('UY','URUGUAY','Uruguay','URY','858', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('UZ','UZBEKISTAN','Uzbekistan','UZB','860', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('VU','VANUATU','Vanuatu','VUT','548', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('VE','VENEZUELA','Venezuela','VEN','862', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('VN','VIET NAM','Viet Nam','VNM','704', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('VG','VIRGIN ISLANDS, BRITISH','Virgin Islands, British','VGB','092', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('VI','VIRGIN ISLANDS, U.S.','Virgin Islands, U.s.','VIR','850', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('WF','WALLIS AND FUTUNA','Wallis and Futuna','WLF','876', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('EH','WESTERN SAHARA','Western Sahara','ESH','732', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('YE','YEMEN','Yemen','YEM','887', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('ZM','ZAMBIA','Zambia','ZMB','894', true);
INSERT INTO countries(id, name, printable_name, iso3, num_code, is_active) VALUES ('ZW','ZIMBABWE','Zimbabwe','ZWE','716', true);

/* PRODUCT CATEGORIES */
-- grind

/*<select class="single-option-selector single-option-selector-product-template product-form__input" id="SingleOptionSelector-0" data-index="option1">
                      
                        <option value="Espresso" selected="selected">Espresso</option>
                      
                        <option value="Whole Bean">Whole Bean</option>
                      
                        <option value="Autodrip">Autodrip</option>
                      
                        <option value="French Press">French Press</option>
                      
                    </select>*/

insert into product_categories(name_key, description_key, image_class, is_active) 
values('Dic.ProductCategory.RoastTypeName', 'Dic.ProducatCategory.RoadTypeDescKey', 'product-category-roast-type', true);
insert into product_categories(name_key, description_key, image_class, is_active) 
values('Dic.ProductCategory.RoastTypeName', 'Dic.ProducatCategory.RoadTypeDescKey', 'product-category-roast-type', true);

-- insert into users(id) values